services:
  - type: web
    name: sg-fibra-cadastro
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SGP_URL
        value: https://sgfibra.sgp.tsmx.app
      - key: SGP_APP
        sync: false
      - key: SGP_TOKEN
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DAILY_LIMIT
        value: 2
      - key: PRECADASTRO_ATIVAR
        value: true
      - key: PUBLIC_BASE_URL
        value: https://cadastro.sgfibra.com.br
      - key: CONTRACT_POP_ID
        value: 1
      - key: CONTRACT_NAS_ID
        value: 1
      - key: CONTRACT_PORTADOR_ID
        value: 1
      - key: CONTRACT_FORMACOBRANCA_ID
        value: 6
      - key: CONTRACT_VENCIMENTO_DIA
        value: 10
      - key: CONTRACT_VENCIMENTO_ID
        value: 2
      - key: CONTRACT_MODOAQUISICAO
        value: 1
      - key: CONTRACT_OS_INSTALACAO
        value: true
      - key: DEFAULT_MAP_LL
        value: ""
      - key: PLANS_JSON
        value: '{"300":{"id":1,"name":"300 Mega"},"500":{"id":3,"name":"500 Mega"},"700":{"id":4,"name":"700 Mega"}}'
      - key: INSTALLATION_SERVICE_DESCRIPTION
        value: ""
      - key: CONFIRMATION_EMAIL_ENABLED
        value: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 465
      - key: SMTP_SECURE
        value: true
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: SMTP_REPLY_TO
        sync: false
